const CONSTANTS = {};

CONSTANTS.LANGUAGE_EN = 'en';
CONSTANTS.LANGUAGE_ES = 'es';
CONSTANTS.AVAILABLE_LANGUAGES = [CONSTANTS.LANGUAGE_EN, CONSTANTS.LANGUAGE_ES];

// ACTIONS
// AUTH
CONSTANTS.ACTION_CLEAN_AUTH = 'ACTION_CLEAN_AUTH';
CONSTANTS.ACTION_LOGIN = 'ACTION_LOGIN';

export default CONSTANTS;
